In [4]:
# --- Read & Inspect ---
import polars as pl
df = pl.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

print(df.head())
print(df.shape)
print(df.describe())

shape: (5, 5)
┌──────────────┬───────┬───────┬─────┬───────┐
│ Name         ┆ Marks ┆ Hours ┆ Age ┆ Sleep │
│ ---          ┆ ---   ┆ ---   ┆ --- ┆ ---   │
│ str          ┆ f64   ┆ f64   ┆ i64 ┆ f64   │
╞══════════════╪═══════╪═══════╪═════╪═══════╡
│ Student_0001 ┆ 55.7  ┆ 5.3   ┆ 21  ┆ 6.2   │
│ Student_0002 ┆ 63.2  ┆ 5.9   ┆ 20  ┆ 6.8   │
│ Student_0003 ┆ 59.9  ┆ 6.2   ┆ 21  ┆ 6.0   │
│ Student_0004 ┆ 64.7  ┆ 6.5   ┆ 23  ┆ 6.6   │
│ Student_0005 ┆ 59.9  ┆ 5.2   ┆ 20  ┆ 4.7   │
└──────────────┴───────┴───────┴─────┴───────┘
(2000, 5)
shape: (9, 6)
┌────────────┬──────────────┬──────────┬──────────┬──────────┬──────────┐
│ statistic  ┆ Name         ┆ Marks    ┆ Hours    ┆ Age      ┆ Sleep    │
│ ---        ┆ ---          ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str          ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪══════════════╪══════════╪══════════╪══════════╪══════════╡
│ count      ┆ 2000         ┆ 2000.0   ┆ 2000.0   ┆ 2000.0   ┆ 2000.0   │
│ null_count ┆ 0            ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0      │
│ mean       ┆ null         ┆ 68.40495 ┆ 5.8552   ┆ 20.101   ┆ 6.9887   │
│ std        ┆ null         ┆ 9.161322 ┆ 1.051226 ┆ 1.954152 ┆ 1.197668 │
│ min        ┆ Student_0001 ┆ 38.1     ┆ 2.5      ┆ 16.0     ┆ 3.4      │
│ 25%        ┆ null         ┆ 62.0     ┆ 5.2      ┆ 19.0     ┆ 6.1      │
│ 50%        ┆ null         ┆ 68.2     ┆ 5.9      ┆ 20.0     ┆ 7.0      │
│ 75%        ┆ null         ┆ 74.5     ┆ 6.6      ┆ 21.0     ┆ 7.8      │
│ max        ┆ Student_2000 ┆ 97.3     ┆ 9.5      ┆ 28.0     ┆ 10.0     │
└────────────┴──────────────┴──────────┴──────────┴──────────┴──────────┘

In [ ]:
# --- Selection & Extraction ---
import polars as pl
df = pl.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

df["Marks"][2]     #--> Get specific value
df.row(2)          #--> Get specific row
df["Age"]          #--> Get specific column
df.slice(1,3)      #--> Get specific group of rows
df.select(["Name", "Marks"])  #--> Get specific group of columns
df.slice(1,3).select(["Name", "Marks"]) #--> Get specific rows & columns

shape: (3, 2)
┌──────────────┬───────┐
│ Name         ┆ Marks │
│ ---          ┆ ---   │
│ str          ┆ f64   │
╞══════════════╪═══════╡
│ Student_0002 ┆ 63.2  │
│ Student_0003 ┆ 59.9  │
│ Student_0004 ┆ 64.7  │
└──────────────┴───────┘

In [ ]:
# --- Filter & Condition ---
import polars as pl
df = pl.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

df1 = df.filter(df["Age"] > 25)
df2 = df.filter(df["Name"]=="Student_0003")

shape: (1, 5)
┌──────────────┬───────┬───────┬─────┬───────┐
│ Name         ┆ Marks ┆ Hours ┆ Age ┆ Sleep │
│ ---          ┆ ---   ┆ ---   ┆ --- ┆ ---   │
│ str          ┆ f64   ┆ f64   ┆ i64 ┆ f64   │
╞══════════════╪═══════╪═══════╪═════╪═══════╡
│ Student_0003 ┆ 59.9  ┆ 6.2   ┆ 21  ┆ 6.0   │
└──────────────┴───────┴───────┴─────┴───────┘